### ISSUE TITLE
Missing Gui Elements

### ISSUE THREAD

**Issue by PeterMitrano** [Cheddarpuffs/Aeneas-KabaSuji#2]
- [x] no build level view
- [x] no stars on select level view
- [x] no file browser for open files in build select level view
- [x] specify board size easily
- [x] change level type in builder
- [x] create and delete hints
- [x] add release numbers
- [x] Color picker for release things
- [x] change time for lightening level
- [x] undo redo buttons on builder
- [x] clearer button/gui stuff for open level file
- [x] create removable widgets for the play level so different level types have different stuff
- [ ] Pop up for winning levels instead of auto-ejecting
- [ ] Preview

**Comment by PeterMitrano** [comment]
Everyone add list of missing gui features here

**Comment by garrisonhefter** [comment]
specify board size is done

**Comment by garrisonhefter** [comment]
Added undo/redo buttons to builder

**Comment by garrisonhefter** [comment]
Decided not to do create/delete hint buttons
