### ISSUE TITLE
Allow builder to set attributes in Level Builder

### ISSUE THREAD

**Issue by jkuszmaul** [Cheddarpuffs/Aeneas-KabaSuji#24]
Currently, the builder can not actually set the attributes (Level type, timeout, number of moves left, etc.) in the level builder. The GUI elements are there, but they need to actually make something happen.

**Comment by PeterMitrano** [comment]
Currently the only truly missing element is release number (their location and value, we have their color).
These elements need to be turned on/off depending on level type
level type selector is also not sexy enough.
