### ISSUE TITLE
Make selecting a level actually open that level

### ISSUE THREAD

**Issue by jkuszmaul** [Cheddarpuffs/Aeneas-KabaSuji#26]
Currently, clicking on a level in the selection screen doesn't actually open a useful level. Also, locked levels should be able to be opened.

**Comment by PeterMitrano** [comment]
Correction: it does open the correct level number, but all levels right now are the same. AKA their models are kinda empty

also note clicking on locked levels is fixed in #32

**Comment by PeterMitrano** [comment]
fixed by #65
