### ISSUE TITLE
Make drag & drop work

### ISSUE THREAD

**Issue by jkuszmaul** [Cheddarpuffs/Aeneas-KabaSuji#27]
Peter has the initial stuff for drag and drop, but it currently doesn't actually do anything with the pieces being dragged.

**Comment by PeterMitrano** [comment]
- Controller for drop on boardView needs to actually add the piece
- Controller for drop also needs to know what kind of level is it
- Controller for start drag also needs to know what level it is

**Comment by jkuszmaul** [comment]
Snapping
