### ISSUE TITLE
Test framework for GUI

### ISSUE THREAD

**Issue by jkuszmaul** [Cheddarpuffs/Aeneas-KabaSuji#34]
We do not currently have a way to test any of the GUI elements.

**Comment by jkuszmaul** [comment]
We need to have some sort of testing (both because we should and because we will need it to get to 80%) for the GUI elements--What will that be?

**Comment by PeterMitrano** [comment]
You're right, I forgot about the coverage requirement.... 
we can absolutely use testFX, but we will have to keep it separate from eclipse, and ask that hineman use gradle to run them. This seems like a reasonable request.
