### ISSUE TITLE
Complete undo/redo support 

### ISSUE THREAD

**Issue by jkuszmaul** [Cheddarpuffs/Aeneas-KabaSuji#36]
- catch key events (or create buttons) 
- put framework in place to track `IMove` classes
- actually call undo/do functions on stored classes

**Comment by garrisonhefter** [comment]
I added Undo/Redo buttons to the Buider GUI

**Comment by PeterMitrano** [comment]
Current bugs:
- [ ] Hints can be undo, but they are left on the board
- [ ] Moving ReleaseNumbers may not work
- [ ] Add piece to bullpen, then delete piece. undo, then undo again. The second undo will fail
