### ISSUE TITLE
Implement and test model classes

### ISSUE THREAD

**Issue by jpmartin2** [Cheddarpuffs/Aeneas-KabaSuji#37]
Right now, the model classes don't really do anything. They'll need to be implemented and tested.

**Comment by jkuszmaul** [comment]
What's missing now that #43 is merged?

**Comment by jpmartin2** [comment]
I think mostly just some more tests. Some of which would be easier to implement once pice factory is implemented - which I think someone was working on.

**Comment by PeterMitrano** [comment]
Piece factory coming soon to a kabasuji near you

**Comment by jpmartin2** [comment]
I think I'm going to close this issue for now, since most of the core functionality is implemented. We can open a separate issue later for tests.
