### ISSUE TITLE
Add hints

### ISSUE THREAD

**Issue by PeterMitrano** [Cheddarpuffs/Aeneas-KabaSuji#56]
hints are totally missing right now
- set hints in builder
- display hints in builder & player (no idea how we want to do this)

**Comment by garrisonhefter** [comment]
We now have it so that you can right click on a piece in the bullpen (in builder) and make it a hint. This should change its color. The piece now has a hint attribute to know whether or not it is a hint

**Comment by garrisonhefter** [comment]
The piece now correctly changes color when you tell it that it's a hint and the flag sets correctly

**Comment by PeterMitrano** [comment]
is there a PR (pull request) for this?
