### ISSUE TITLE
G.Imp Phase 2 4/27

### ISSUE THREAD

**Issue by garrisonhefter** [Cheddarpuffs/Aeneas-KabaSuji#68]
- [x] Drag and Drop fixes (having the pieces return correctly)   @LordPython 
- [x] Defaut directory for saving levels needs to be where they are loading from @jkuszmaul 
- [x] Correctly reindex levels for the play select level screen  @LordPython 
- [x] having the correct level style play at the right time 
- [x] decrements moves when you make a move (puzzle) @jkuszmaul 
- [x] Get timer stuff working @LordPython
- [x] Make sure stars display correctly @LordPython
- [x] Changing Board Size @jkuszmaul 
- [x] Stars 
- [x] Have play level view actually do stuff @PeterMitrano
- [ ] Make the stars save across sessions (save default levels to disc)
- [ ] Achievements? (optional)

**Comment by PeterMitrano** [comment]
not useful anymore. too general
